### PR TITLE
Formatting the docs

### PR DESCRIPTION
**Pull request by samuel-tate**
## Related Issue

#23 

The goal of this issue is to make the `pyrefinebio` docs look more like the [refine.bio docs](http://docs.refine.bio/en/latest/index.html)

## Screenshots

<details>
<summary>Home Page</summary>
<p>

image

</p>
</details>

<details>
<summary>Quickstart</summary>
<p>

image

</p>
</details>

<details>
<summary>Class Pages</summary>
<p>

I think the class pages look a lot better:

image

Especially the `keyword arguments` section for the `search` methods:

image

</p>
</details>

### CODE REVIEW

**Review by dvenprasad — CHANGES_REQUESTED** [review]
Woohoo! They styles match! 

A few minor formatting things:

**- We should add the refine.bio logo on that page too. `pyrefinebio` -> `pyrefine.bio` Could we have `refine.bio` in the logo in Lato so it in in line with the style guide**

- Screen Shot 2021-03-24 at 2 30 41 PM

**The highlighted bit is just floating in space, could we align it to the left?**

**- Can we have the parameters - descriptions formatted consistently? It's different in Quickstart and in classes. The way it is formatted in classes is good. Could we format the parameters in Quickstart in that style?** 

Ex: 
Screen Shot 2021-03-24 at 2 33 41 PM


- **This is kinda squished up. Can we use the below format so that we use the real estate available to us?** 
```  
Returns
< stuff >
 Keyword Arguments
< list > 
``` 

Screen Shot 2021-03-24 at 2 41 08 PM


- **Some of the code chunks are big and user will have to scroll to see all of it. Is there anything we can do make more of it visible or less bad?**

**Review by davidsmejia — APPROVED** [review]
LGTM maybe delete the .DS_Store and add to .gitignore?

**Comment by samuel-tate** [comment]
@dvenprasad 

Ok I just pushed some changes:

>  We should add the refine.bio logo on that page too. pyrefinebio -> pyrefine.bio...

I updated the logo to include the double helix logo and changed the comic sans to Lato
LMK what you think!

> The highlighted bit is just floating in space, could we align it to the left?

The weird formatting you're seeing with the `>>classes>>ProcessorJob` thing might be a result of a versioning mismatch

I was getting that weird formatting when I was using the most up to date version of `sphinx-rtd-theme` because they decided to add a nice little home icon instead of the text `docs` in that location

unfortunately, the home icon used the same css classname as the logo which meant that they were both getting the same styling which was bad

To fix the bad formatting, make sure you're using `sphinx-rtd-theme` 0.4.1

You can do a 
```
pip uninstall -y sphinx-rtd-theme; pip install sphinx-rtd-theme==0.4.1
``` 
to get the  version I'm using

lmk if this fixes the weird formatting

> Can we have the parameters - descriptions formatted consistently? It's different in Quickstart...

I updated the formatting in quickstart and cli.
LMK if you like the changes

> This is kinda squished up. Can we use the below format so that we use the real estate available to us?

This formatting might also get fixed with a downgrade of the theme version - mine looks different

> Some of the code chunks are big and user will have to scroll to see all of it. Is there...

I enabled wrapping in the code blocks.
Some of them look a bit weird now - lmk if you like this better or if we should go back to the scrolling.
I can continue looking to see if there's a better solution as well.

**Review by dvenprasad — CHANGES_REQUESTED** [review]
Okay, 

- the logo is better now, thank you! 
- So updated the theme and formatting issues are resolved 🎉 
- The formatting in Quickstart and CLI looks good! 
- The wrap in code blocks looks good to me. Was there specific code blocks for which you thought looked particularly bad? 

Sorry, I just realized that we don't link back to the the repo. Could we change the `View page source` to link to the pyrefinebio github repo? 

Not sure how hard this is but, it would be nice to have a `Back to refine.bio` button too like on refine.bio docs
Screen Shot 2021-03-25 at 4 53 48 PM

**Comment by samuel-tate** [comment]
@dvenprasad 

I just pushed some new changes:

- added `back to refine.bio` button
- changed `View page source` to `Edit on GitHub` and the link links to this repo

The weird wrapping only really happened in the big code block in `Quickstart/Getting Help`.
Check it out and lmk what you think!

**Review by dvenprasad — APPROVED** [review]
Woohoo! Looks good, well done :)

**Pull request merged**
