### PR TITLE
Handle api's new standardized errors

### PR DESCRIPTION
**Pull request by samuel-tate**
See AlexsLemonade/refinebio#2597 for the standardized errors.

## Stack Trace Screenshots:

<details><summary>Handling Filter Type Errors</summary>
<p>

image

</p>
</details>

<details><summary>Handling Multiple Errors</summary>
<p>

image

</p>
</details>

</p>
</details>

<details><summary>Handling Invalid Data 1</summary>
<p>

image

</p>
</details>

<details><summary>Handling Invalid Data 2</summary>
<p>

image

</p>
</details>

### CODE REVIEW

**Review by kurtwheeler — COMMENTED** [review]
This looks great! I'd love to see what the exception messages and/or stack traces look like before approving it though!

**Review by kurtwheeler — APPROVED** [review]
These look great to me!!!!

**Comment by samuel-tate** [comment]
gonna hold off on merging this PR until the new api errors are in prod

**Comment by kurtwheeler** [comment]
There was a successful refinebio deploy so you should rerun these tests!

**Review by kurtwheeler — APPROVED** [review]
Sweet!! This passes and looks good!

**Pull request merged**
